server:
  address: 0.0.0.0
  port: 1000

spring:
  application:    name: Cloud-Authorization-Server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.111:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Hongkong
    username: root
    password: centos7
    continue-on-error: false
    name: MYSQL
    platform: all

  jmx:
    enabled: false

#  redis:
#    host: 192.168.2.105
#    port: 6379

  mail:
      host: smtp.126.com
      port: 465
      username: ewdaoyuan@126.com
      password: ewdy123456
      protocol: smtp
      default-encoding: UTF-8
      properties:
          mail.smtp.auth: true
          mail.smtp.starttls.enable: true
          mail.smtp.starttls.required: true
          mail.smtp.socketFactory.port: 465
          mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
          mail.smtp.socketFactory.fallback: false

#mybatis:
#  type-handlers-package: com.bms.api.handlers

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://admin:123456@localhost:7001/eureka/
#       defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,  http://eureka7003.com:7003/eureka/ 
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true     #访问路径可以显示IP地址 
    metadata-map:
      user.name: admin
      user.password: TwjyySf4FQEzoqeGctmsr0E6z6yOpOMY6qA9dA1BryFZGMZAaj0oOzj5kTYuRbm8QTaQwzX+j68BOyzjs4yPxj9w9VVoMg6jXbH0E3JqHHdExEnd6DArudmu0M2kPoSdM8pAvpK7znvwWanZ0CQgtMZv7aH/UkN/AXNVQZSnKBk=
    
management:
  endpoints:
    web:
      exposure:
       include: "*" 

#验证码设置
#com:
#  dy:
#    security:
#      code:
#        sms:
#          length: 6
#          expireIn: 300
#          interval: 60
#          url: /bindMobile/**,/upMobile/**,/validateCode/sms
#        email:
#          length: 6
#          expireIn: 300
#          interval: 60
#          url: /bindEmail/**,/upEmail/**,/validateCode/email
#        image:
#          length: 4
#          expireIn: 300
#          url: /loginll
#      social:
#        filterProcessesUrl: /qqLogin
#        qq:
#          app-id: wxd99431bbff8305a0
#          app-secret: 60f78681d063590a469f1b297feff3c4
#        weixin:
#          app-id: wxd99431bbff8305a0
#          app-secret: 60f78681d063590a469f1b297feff3c4



#file:
#  upload:
#    size: 100 #文件上传大小
#    path: /home/project/bms  #文件存放路径


logging:
  level:
    com.bms: debug

#本服务的说明 
info: 
  app.name: ${spring.application.name}
  company.name: www.dy.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"