server:
  port: 7001
  
spring:
  application:
    name:  "@project.artifactId@"
  main: 
    allow-bean-definition-overriding: true
  mail:    host: smtp.qq.com
    port: 465
    username: 891713908@qq.com
    password: ljvzqmyklxjubdgd
    default-encoding: UTF-8
    properties:      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
eureka: 
  instance:
    hostname: localhost #eureka服务端的实例名称
    instance-id: ${spring.application.name}
    prefer-ip-address: true #    environment: 
#    data-center-info: 
  client: 
    register-with-eureka: false           #false表示不向注册中心注册自己。
    fetch-registry: false                 #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      defaultZone: ENC(/I61py2c3LIqOAvZmF6pydpTtN1X0W9IScWU4fhvYxLL4durx4CFAeT1y5f1U7oEkrd4hQ6ygfE=)   #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/     #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  server:
    enable-self-preservation: false        # 为false禁用eureka的自我保护机制    eviction-interval-timer-in-ms: 4000
    
com:  dy:    mail: 
      subject: service outage!!!  #邮件主题
      receivers: 752401007@qq.com,891713908@qq.com  #固定接收人群
      max-count: 50 #单次最大群发数
      retry-count: 3 #发送失败重发次数
    
#本服务的说明 
info: 
  app.name: ${spring.application.name}
  company.name: www.dy.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
#  build.start: nohup java -jar XX.jar > XX.out 2>&1 &
