server:
  port: 4001

spring:
  application:
    name: "@project.artifactId@"
  main:
    allow-bean-definition-overriding: true
  boot:    admin:      monitor:        status-interval: 5000 #每5秒更新client的状态
#      instance-proxy:#        ignored-headers:#        - ""
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
        
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url:     
      defaultZone: ENC(e9qKnB2ANTJmCS8kfF3ZvQC2THlPdaOdoIplsMxRR21Dx/iVnyxLa4pP+CupBwg4flXb1LTAWXw=) 
#       defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,  http://eureka7003.com:7003/eureka/ 
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true     #访问路径可以显示IP地址     metadata-map:
      user.name: ENC(+8Qi/AE8/qMVBp/cfbK21Q==)
      user.password: ENC(x8RkFh6daB/KpSO8pB9pjQ==)
      
#本服务的说明 
info: 
  app.name: ${spring.application.name}
  company.name: www.dy.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
