server:
  port: 4001

spring:
  application:
    name: "@project.artifactId@"
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: user
      password: 111      roles: admin
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
        
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://user:111@localhost:7001/eureka/ 
#       defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,  http://eureka7003.com:7003/eureka/ 
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true     #访问路径可以显示IP地址     metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password} 
      
#本服务的说明 
info: 
  app.name: ${spring.application.name}
  company.name: www.dy.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"
