server:
  port: 8001
  
spring: 
  application:    name: "microservice-common-provider"
  main:
    allow-bean-definition-overriding: true
    
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: ENC(/I61py2c3LIqOAvZmF6pydpTtN1X0W9IScWU4fhvYxLL4durx4CFAeT1y5f1U7oEkrd4hQ6ygfE=) 
#       defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,  http://eureka7003.com:7003/eureka/ 
  instance:
    instance-id: "microservice-common-provider"
    prefer-ip-address: true     #访问路径可以显示IP地址 
    
feign:
  hystrix:
    enabled: true  
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
      