server:
  port: 80
  
spring:
  application:
    name: "microservice-common-consumer"
  main:    allow-bean-definition-overriding: true

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://user:111@localhost:7001/eureka/
  instance:
    instance-id: "microservice-common-consumer"
    prefer-ip-address: true     #访问路径可以显示IP地址 

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
feign: 
  hystrix: 
    enabled: true
    
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          strategy: S
    
info: 
  app.name: "microservice-common-consumer"
  company.name: www.dy.com
  build.artifactId: "microservice-common-consumer"
  build.version: "1.0-SNAPSHOT"