server:
  port: 80
  
spring:
  application:
    name: "@project.artifactId@"
  main:    allow-bean-definition-overriding: true

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
#      defaultZone: ENC(/I61py2c3LIqOAvZmF6pydpTtN1X0W9IScWU4fhvYxLL4durx4CFAeT1y5f1U7oEkrd4hQ6ygfE=)  
      defaultZone: ENC(Vc2+db9YK6J+YbmdpIfjJFNZKuCgpmcilhDqAzJT4R/lXxE+nvkBNHoOXf+EwvHAib7DA14ssz8=)
  instance:
    instance-id: "@project.artifactId@"
    prefer-ip-address: true     #访问路径可以显示IP地址 

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
feign: 
  hystrix: 
    enabled: true
    
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          strategy: S
    
info: 
  app.name: "@project.artifactId@"
  company.name: www.dy.com
  build.artifactId: "@project.artifactId@"
  build.version: "@project.version@"