server:
  port: 4001

spring:
  application:
    name: "microservice-admin-server"
  main:
    allow-bean-definition-overriding: true
#  security:#    user:#      name: ENC(+8Qi/AE8/qMVBp/cfbK21Q==)#      password: ENC(x8RkFh6daB/KpSO8pB9pjQ==)
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Hongkong
    username: root
    password: dy123456
    continue-on-error: false
    name: MYSQL
    platform: all
  jmx:
    enabled: false
        
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
        
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url:     
      defaultZone: http://admin:123456@localhost:7001/eureka/ 
#       defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,  http://eureka7003.com:7003/eureka/ 
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true     #访问路径可以显示IP地址     metadata-map:
      user.name: ENC(+8Qi/AE8/qMVBp/cfbK21Q==)
      user.password: ENC(x8RkFh6daB/KpSO8pB9pjQ==)
      
com: 
  dy: 
    security: 
      browser: 
        loginType: REDIRECT

      
#本服务的说明 
info: 
  app.name: ${spring.application.name}
  company.name: www.dy.com
  build.artifactId: "microservice-admin-server"
  build.version: "1.0-SNAPSHOT"
