server:
  port: 7001
  
spring:
  application:
    name:  "@project.artifactId@"
  main: 
    allow-bean-definition-overriding: true
  redis:#    host: 192.168.2.111
#    port: 6379
    cluster:      nodes: 192.168.2.111:6379
      max-redirects: 1
