server: 
  port: 3344 
  
spring:
  application:
    name:  Cloud-Config
  cloud:
    config:
      server:        git:
#          uri: git@github.com:shily007/cloud-config.git #GitHub上面的git仓库名字          uri: https://github.com/shily007/cloud-config.git #GitHub上面的git仓库名字
  security:    user:      name: user
      password: 111
      management:  endpoints:    web:      exposure:        include: refresh,health,info
        
eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://user:111@localhost:7001/eureka/
#       defaultZone: http://eureka7001.com:7001/eureka/ #,http://eureka7002.com:7002/eureka/,  http://eureka7003.com:7003/eureka/ 
  instance:
    instance-id: "@project.artifactId@"
    prefer-ip-address: true     #访问路径可以显示IP地址 